flowchart LR



classDef S1 stroke:#993388
classDef S2 stroke:#ee0066
classDef S3 stroke:#dd0000
classDef S4 stroke:#ff8340
classDef S5 stroke:#ffc753
classDef S6 stroke:#77bb11
classDef S7 stroke:#118888
classDef S8 stroke:#004282
classDef S9 stroke:#c0c0c0
classDef S10 stroke:#404040
classDef S11 stroke:#a0e0e0
classDef S12 stroke:#e060e0
classDef S13 stroke:#6060e0
classDef S14 stroke:#e0e060
classDef S15 stroke:#60e060
classDef S16 stroke:#206060
classDef S17 stroke:#e0a0e0
classDef S18 stroke:#60e0e0
classDef S19 stroke:#a060e0
classDef S20 stroke:#2060e0
classDef S21 stroke:#a0e060

SD-7-5-1@{ shape: hex } --- S1
SD-7-5-2@{ shape: hex } --- S19
SD-7-5-3@{ shape: hex } --- S6
SD-7-5-4@{ shape: hex } --- S16
SD-7-5-5@{ shape: hex } --- S11

S1:::S1 -- 120 --> S2:::S2 -- 120 --> S3:::S3 -- 120 --> S4:::S4 -- 545 --> S5:::S5
S19:::S19 -- 115 --> S20:::S20 -- 115 --> S21:::S21 -- 115 --> S15:::S15 -- 180 --> S10:::S10 -- 425 --> S4
S11:::S11 -- 65 --> S12:::S12 -- 65 --> S13:::S13 -- 65 --> S14:::S14 -- 65 --> S15
S6:::S6 -- 115 --> S7:::S7 -- 115 --> S8:::S8 -- 115 --> S9:::S9 -- 245 --> S10
S16:::S16 -- 130 --> S17:::S17 -- 130 --> S18:::S18 -- 130 --> S9